const supervisors = [
	{
		id: 1,
		firstName: "Alfred",
		lastName: "Merrickville",
		state: "NSW",
		postcode: "2000",
		employer: "N/A",
		phone: "0423234432",
	},
	{
		id: 2,
		firstName: "Jenny",
		lastName: "Rae",
		state: "ACT",
		postcode: "3450",
		employer: "Canberra Fitness",
		phone: "0433674367",
	},
	{
		id: 3,
		firstName: "Gregory",
		lastName: "Munch",
		state: "NSW",
		postcode: "2037",
		employer: "Darghan Crossfit",
		phone: "0499747754",
	},
	{
		id: 4,
		firstName: "Daniel",
		lastName: "Palmer",
		state: "QLD",
		postcode: "1234",
		employer: "N/A ",
		phone: "0423458875",
	},
	{
		id: 5,
		firstName: "Nathan",
		lastName: "Thomson",
		state: "NSW",
		postcode: "2900",
		employer: "N/A ",
		phone: "0423434532",
	},
	{
		id: 6,
		firstName: "Lily",
		lastName: "Aldrich",
		state: "QLD",
		postcode: "6489",
		employer: "Sunshine Gym",
		phone: "0456364564",
	},
];

export default supervisors;
